@startuml

interface Iterator {
    + rewind() : void
    + valid() : bool
    + next() : void
    + key() : mixed
    + current() : mixed
}

class NumbersSquared {
    - start : int
    - end : int
    - current : int

    + __construct(start, end)
    + rewind() : void
    + valid() : bool
    + next() : void
    + key() : mixed
    + current() : float|int
}

Iterator <|.. NumbersSquared : implements

@enduml
